# Generated by Django 5.2.7 on 2025-10-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(choices=[('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('12:00-14:00', '12:00 - 14:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00'), ('18:00-20:00', '18:00 - 20:00'), ('20:00-22:00', '20:00 - 22:00'), ('22:00-00:00', '22:00 - 00:00'), ('00:00-02:00', '00:00 - 02:00'), ('02:00-04:00', '02:00 - 04:00'), ('04:00-06:00', '04:00 - 06:00'), ('06:00-08:00', '06:00 - 08:00')], max_length=15),
        ),
    ]
