# Generated by Django 5.2.7 on 2025-11-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_timeslot_is_active_alter_timeslot_time_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
